CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "login" varchar,
  "name" varchar,
  "birthday" date
);

CREATE TABLE "friendship" (
  "user_id" bigint,
  "friend_id" bigint,
  "confirmed" boolean
);

CREATE TABLE "films" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar(200),
  "release_date" date,
  "duration" int,
  "rating_id" bigint
);

CREATE TABLE "film_genres" (
  "film_id" bigint,
  "genre_id" bigint
);

CREATE TABLE "genres" (
  "id" bigint PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "ratings" (
  "id" bigint PRIMARY KEY,
  "name" varchar(10)
);

CREATE TABLE "likes" (
  "user_id" bigint,
  "film_id" bigint
);

ALTER TABLE "friendship" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "friendship" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("id");

ALTER TABLE "films" ADD FOREIGN KEY ("rating_id") REFERENCES "ratings" ("id");

ALTER TABLE "film_genres" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");

ALTER TABLE "film_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("id");
